### ISSUE TITLE
ximgproc module on Android?

### ISSUE THREAD

**Issue by wangzeyu961130** [richdyang/opencv3-android-sdk-with-contrib#2]
Hi Chao,

Your repository is one of the most useful resources that I've found so far for building opencv_contrib on Android. However, there is no ximgproc module in opencv3-android-sdk-with-contrib/OpenCV-android-sdk/sdk/java/src/org/opencv/. I'd appreciate it if you could upload it or refer me to any tutorials about how to build them from the source code. Thanks!

**Comment by richdyang** [comment]
Yes, I can. I will check why `ximgproc` in opencv_contrib are not compiled into the SDK. I will reply you later.

**Comment by richdyang** [comment]
@wangzeyu961130 I rebuilt the SDK with latest code. You can download it. it should be working.

**Comment by wangzeyu961130** [comment]
Thanks a lot! It's working perfectly.
